name: CI Terraform

on:
  pull_request:
    paths:
      - 'bia/infra/terraform/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bia/infra/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 🚀 Cache de plugins
      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Fmt
        run: terraform fmt -check -diff

      - name: Terraform Validate
        run: terraform validate

      # tfvars e env correto
      - name: Terraform Plan
        env:
          TF_VAR_n8n_password: ${{ secrets.N8N_PASSWORD }}
        run: terraform plan -input=false -no-color -var-file="terraform.tfvars"