name: Deploy DEV

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t digifusion-bia -f bia/docker/Dockerfile ./bia

      - name: Teste
        run: echo "Docker build realizado com sucesso!"